export {
  DEFAULT_CONSENT_DOCUMENT_VERSION,
  EMAIL_VERIFICATION_RESEND_COOLDOWN_MS,
  EMAIL_VERIFICATION_RESEND_PATH,
} from './auth';
export {
  PRIVACY_POLICY_URL,
  TERMS_DOCUMENT_BLOCKS,
  TERMS_OF_SERVICE_URL,
  TERMS_PLACEHOLDER_BODY,
  type TermsDocumentBlock,
} from './legal';
